loss_weight_1: 0.14
loss_weight_2: 0.86
cuda: False
batch_size: 128
test_batch_size: 64
hidden_dim_1: 240
hidden_dim_2: 254
hidden_dim_3: 220
dropout_input: 0.2
dropout_hidden: 0.5
lr: 0.003
epochs: 100
seed: 0